/**
 * "Unfilled & flagged shifts" panel — ported from public/duty-roster/index.html's
 * renderConflicts() (lines ~3551-3559).
 */
import type { TFunction } from "i18next";
import type { MonthState, GenerateMonthResult } from "./types";
import type { GenerateMonthConfig } from "./schedulingEngine";
import { guardName } from "./rosterModel";

export interface ConflictItem {
  /** Prefix text before the (originally bolded) shift label. */
  before: string;
  /** The shift label — bolded in the original via <strong>. */
  shiftLabel: string;
  /** Suffix text after the shift label. */
  after: string;
}

export function buildConflictItems(config: GenerateMonthConfig, ms: MonthState, result: GenerateMonthResult, t: TFunction): ConflictItem[] {
  const items: ConflictItem[] = [];
  result.conflicts.forEach((c) => {
    items.push({
      before: t("dutyRoster.conflictsPanel.noEligibleGuardFor"),
      shiftLabel: c.shiftLabel,
      after: t("dutyRoster.conflictsPanel.slotOnDate", { slot: c.slot + 1, date: c.date }),
    });
  });
  result.flags.forEach((f) => {
    items.push({
      before: t("dutyRoster.conflictsPanel.guardOn", { name: guardName(config, ms, f.guardId) }),
      shiftLabel: f.shiftLabel,
      // f.reason is diagnostic text generated by the scheduling engine (schedulingEngine.ts),
      // not translated — see this app's Duty Roster i18n scope note (kept in English like the
      // permanent activity log, rather than translating every reason string the algorithm can
      // produce).
      after: t("dutyRoster.conflictsPanel.slotDateReason", { slot: f.slot + 1, date: f.date, reason: f.reason }),
    });
  });
  return items;
}
